package org.tan.api.enums;

public enum EChunkPermission {
    INTERACT_CHEST,
    INTERACT_DOOR,
    BREAK_BLOCK,
    PLACE_BLOCK,
    ATTACK_PASSIVE_MOB,
    INTERACT_BUTTON,
    INTERACT_REDSTONE,
    INTERACT_FURNACE,
    INTERACT_ITEM_FRAME,
    INTERACT_ARMOR_STAND,
    INTERACT_DECORATIVE_BLOCK,
    INTERACT_MUSIC_BLOCK,
    USE_LEAD,
    USE_SHEARS,
    INTERACT_BOAT,
    INTERACT_MINECART,
    USE_BONE_MEAL,
    INTERACT_BERRIES,
}
