package org.tan.api.enums;

public enum ETownPermission {
    
    MANAGE_TAXES,
    CLAIM_CHUNK,
    UNCLAIM_CHUNK,
    UPGRADE_TOWN,
    INVITE_PLAYER,
    KICK_PLAYER,
    CREATE_RANK,
    DELETE_RANK,
    MANAGE_RANKS,
    MANAGE_CLAIM_SETTINGS,
    MANAGE_TOWN_RELATION,
    MANAGE_MOB_SPAWN,
    CREATE_PROPERTY,
    MANAGE_PROPERTY,
    TOWN_ADMINISTRATOR;
}
