package org.leralix.tan.gui.cosmetic;

public enum IconKey {

    TIMEZONE_ICON_DAY,
    TIMEZONE_ICON_NIGHT,
    NATION_BASE_ICON,
    REGION_BASE_ICON,
    TOWN_BASE_ICON,
    PLAYER_BASE_ICON,

    PLAYER_HEAD_ICON,
    PLAYER_BALANCE_ICON,
    PLAYER_PROPERTY_ICON,
    NEWSLETTER_ICON,
    TIMEZONE_BUTTON,
    LANGUAGE_ICON,

    HELP_TRANSLATION_ICON,

    MARK_ALL_AS_READ_ICON,
    CHANGE_NEWSLETTER_SCOPE_ICON,

    CREATE_TOWN_ICON,
    BROWSE_TOWN_ICON,

    CREATE_REGION_ICON,
    BROWSE_REGION_ICON,

    TERRITORY_ICON,
    TERRITORY_TREASURY_ICON,
    TERRITORY_MEMBER_ICON,
    TERRITORY_LAND_ICON,
    TERRITORY_BROWSE_ICON,
    TERRITORY_DIPLOMACY_ICON,
    TERRITORY_LEVEL_ICON,
    TERRITORY_SETTINGS_ICON,
    TERRITORY_BUILDING_ICON,
    TERRITORY_HIERARCHY_ICON,
    TERRITORY_WAR_ICON,

    TOWN_LANDMARKS_ICON,
    TOWN_PROPERTIES_ICON,

    TERRITORY_RENAME_ICON,
    TERRITORY_DESCRIPTION_ICON,
    TERRITORY_CHANGE_OWNER_ICON,
    TERRITORY_CHANGE_COLOR_ICON,

    TOWN_CHANGE_OWNERSHIP_ICON,
    TOWN_ALLOW_APPLICATION_ICON,
    TOWN_DENY_APPLICATION_ICON,
    TOWN_QUIT_TOWN_ICON,
    TOWN_DELETE_TOWN_ICON,

    REGION_CHANGE_OWNERSHIP_ICON,
    REGION_QUIT_REGION_ICON,
    REGION_DELETE_REGION_ICON,

    MANAGE_RANKS_ICON,
    MANAGE_APPLICATIONS_ICON,

    NEW_RANK_ICON,

    PLAYER_LIST_ICON,
    MANAGE_PERMISSION_ICON,
    DECREASE_SALARY_ICON,
    CURRENT_SALARY_ICON,
    INCREASE_SALARY_ICON,
    RENAME_RANK_ICON,
    PAY_TAXES_ICON,
    SET_DEFAULT_ROLE_ICON,
    DELETE_RANK_ICON,

    CHANGE_SCOPE_ICON,

    CREATE_NEW_PROPERTY_ICON,

    PROPERTY_RENAME_ICON,
    PROPERTY_DESCRIPTION_ICON,
    PROPERTY_BOUNDS_ICON,
    SELL_PROPERTY_ICON_NOT_FOR_SALE,
    SELL_PROPERTY_ICON_FOR_SALE,
    RENT_PROPERTY_ICON_NOT_FOR_RENT,
    RENT_PROPERTY_ICON_FOR_RENT,
    RENT_PROPERTY_ICON_RENTED,
    AUTHORIZED_PLAYERS_ICON,
    DELETE_PROPERTY_ICON,

    ADD_PLAYER_ICON,

    CONFIRM_BUY_PROPERTY_ICON,
    CANCEL_BUY_PROPERTY_ICON,

    CONFIRM_RENT_PROPERTY_ICON,
    CANCEL_RENT_PROPERTY_ICON,

    STOP_RENTING_PROPERTY_ICON,

    STRONGHOLD_INFO_ICON,

    BUDGET_ICON,
    MISCELLANEOUS_SPENDING_ICON,
    DONATION_ICON,
    DONATION_HISTORY_ICON,
    RETRIEVE_MONEY_ICON,

    LANDS_PERMISSION_ICON,
    GENERAL_SETTINGS_ICON,
    MOBS_SPAWN_SETTINGS_ICON,

    GUI_MANAGE_CHEST_ACCESS_ICON,
    GUI_INTERACT_DOORS_ACCESS_ICON,
    GUI_BREAK_BLOCK_PERMISSION_ICON,
    GUI_BUILD_BLOCK_PERMISSION_ICON,
    GUI_ATTACK_PASSIVE_MOBS_ICON,
    GUI_PRESS_BUTTON_ICON,
    GUI_USE_REDSTONE_COMPONENT,
    GUI_OPEN_FURNANCE_ICON,
    GUI_INTERACT_ITEM_FRAME_ICON,
    GUI_INTERACT_ARMOR_STAND_ICON,
    GUI_INTERACT_CAULDRON_ICON,
    GUI_INTERACT_MUSIC_ICON,
    GUI_INTERACT_LEAD_ICON,
    GUI_INTERACT_SHEARS_ICON,
    GUI_INTERACT_BOATS_ICON,
    GUI_INTERACT_MINECART_ICON,
    GUI_INTERACT_BONE_MEAL_ICON,
    GUI_INTERACT_GATHER_BERRIES_ICON,

    GUI_MANAGE_TAXES_ICON,
    GUI_CLAIM_CHUNK_ICON,
    GUI_UNCLAIM_CHUNK_ICON,
    GUI_UPGRADE_TOWN_ICON,
    GUI_INVITE_PLAYER_ICON,
    GUI_KICK_PLAYER_ICON,
    GUI_CREATE_RANK_ICON,
    GUI_DELETE_RANK_ICON,
    GUI_MANAGE_RANK_ICON,
    GUI_MANAGE_CLAIMS_ICON,
    GUI_MANAGE_DIPLOMACY_ICON,
    GUI_MANAGE_MOB_SPAWN_ICON,
    GUI_CREATE_PROPERTY_ICON,
    GUI_MANAGE_PROPERTY_ICON,
    GUI_ADMINISTRATOR_ICON,

    REMOVE_WAR_START_TIME_ICON,
    ADD_WAR_START_TIME_ICON,
    WAR_START_TIME_ICON,
    CONFIRM_WAR_START_ICON,
    CONFIRM_WAR_START_IMPOSSIBLE_ICON,

    GUI_CONFIRM_CLAIM_LANDMARK_REQUIREMENTS_MET_ICON,
    GUI_CONFIRM_CLAIM_LANDMARK_REQUIREMENTS_UNMET_ICON,

    FORT_BUILDING_ICON,

    WAR_GOAL_LIST_ICON,
    WAR_CREATE_ATTACK_ICON,
    WAR_ENEMY_GOAL_LIST_ICON,
    WAR_SURRENDER_ICON,



}
