package org.leralix.tan.gui.cosmetic;

public enum IconKey {

    NATION_BASE_ICON,
    REGION_BASE_ICON,
    TOWN_BASE_ICON,
    PLAYER_BASE_ICON,

    PLAYER_HEAD_ICON,
    PLAYER_BALANCE_ICON,
    PLAYER_PROPERTY_ICON,
    NEWSLETTER_ICON,
    LANGUAGE_ICON,

    HELP_TRANSLATION_ICON,

    MARK_ALL_AS_READ_ICON,
    CHANGE_NEWSLETTER_SCOPE_ICON,

    CREATE_TOWN_ICON,
    BROWSE_TOWN_ICON,

    CREATE_REGION_ICON,
    BROWSE_REGION_ICON,

    TERRITORY_ICON,
    TERRITORY_TREASURY_ICON,
    TERRITORY_MEMBER_ICON,
    TERRITORY_LAND_ICON,
    TERRITORY_BROWSE_ICON,
    TERRITORY_DIPLOMACY_ICON,
    TERRITORY_LEVEL_ICON,
    TERRITORY_SETTINGS_ICON,
    TERRITORY_HIERARCHY_ICON,
    TERRITORY_WAR_ICON,

    TOWN_LANDMARKS_ICON,
    TOWN_PROPERTIES_ICON,

    MANAGE_RANKS_ICON,
    MANAGE_APPLICATIONS_ICON,

    NEW_RANK_ICON,

    PLAYER_LIST_ICON,
    MANAGE_PERMISSION_ICON,
    DECREASE_SALARY_ICON,
    CURRENT_SALARY_ICON,
    INCREASE_SALARY_ICON,
    RENAME_RANK_ICON,
    PAY_TAXES_ICON,
    SET_DEFAULT_ROLE_ICON,
    DELETE_RANK_ICON,

    CHANGE_SCOPE_ICON,

    CREATE_NEW_PROPERTY_ICON,

    PROPERTY_RENAME_ICON,
    PROPERTY_DESCRIPTION_ICON,
    PROPERTY_BOUNDS_ICON,
    SELL_PROPERTY_ICON_NOT_FOR_SALE,
    SELL_PROPERTY_ICON_FOR_SALE,
    RENT_PROPERTY_ICON_NOT_FOR_RENT,
    RENT_PROPERTY_ICON_FOR_RENT,
    RENT_PROPERTY_ICON_RENTED,
    AUTHORIZED_PLAYERS_ICON,
    DELETE_PROPERTY_ICON,

    CONFIRM_BUY_PROPERTY_ICON,
    CANCEL_BUY_PROPERTY_ICON,

    CONFIRM_RENT_PROPERTY_ICON,
    CANCEL_RENT_PROPERTY_ICON,

    STOP_RENTING_PROPERTY_ICON,

    STRONGHOLD_INFO_ICON,

    BUDGET_ICON,
    MISCELLANEOUS_SPENDING_ICON,
    DONATION_ICON,
    DONATION_HISTORY_ICON,
    RETRIEVE_MONEY_ICON,


}
