package org.leralix.tan.gui.cosmetic;

public enum IconKey {

    NATION_BASE_ICON,
    REGION_BASE_ICON,
    TOWN_BASE_ICON,
    PLAYER_BASE_ICON,

    PLAYER_HEAD_ICON,
    PLAYER_BALANCE_ICON,
    PLAYER_PROPERTY_ICON,
    NEWSLETTER_ICON,
    LANGUAGE_ICON,

    HELP_TRANSLATION_ICON,

    MARK_ALL_AS_READ_ICON,
    CHANGE_NEWSLETTER_SCOPE_ICON,

    CREATE_TOWN_ICON,
    BROWSE_TOWN_ICON,

    TOWN_ICON,
    TOWN_TREASURY_ICON,
    TOWN_MEMBER_ICON,
    TOWN_LAND_ICON,
    TOWN_BROWSE_ICON,
    TOWN_DIPLOMACY_ICON,
    TOWN_LEVEL_ICON,
    TOWN_SETTINGS_ICON,
    TOWN_PROPERTIES_ICON,
    TOWN_LANDMARKS_ICON,
    TOWN_WAR_ICON,
    TOWN_HIERARCHY_ICON,

    MANAGE_RANKS_ICON,
    MANAGE_APPLICATIONS_ICON,

    NEW_RANK_ICON,

    PLAYER_LIST_ICON,
    MANAGE_PERMISSION_ICON,
    DECREASE_SALARY_ICON,
    CURRENT_SALARY_ICON,
    INCREASE_SALARY_ICON,
    RENAME_RANK_ICON,
    PAY_TAXES_ICON,
    SET_DEFAULT_ROLE_ICON,
    DELETE_RANK_ICON,

    CHANGE_SCOPE_ICON,

    CREATE_NEW_PROPERTY_ICON


}
