name: TownsAndNations
version: '${version}'
main: org.leralix.tan.TownsAndNations
api-version: "1.19"
authors: [ Leralix ]
softdepend: [Vault, PlaceholderAPI]
description: A town plugin with rp tools
commands:
  tan:
    description: base command of Town and Nation
    permission: townandnation.base
    usage: /<command>
  tanadmin:
    description: admin command of Town and Nation
    permission: townandnation.admin
    usage: /<command>
  tandebug:
    description: debug command of Town and Nation
    permission: townandnation.admin
    usage: /<command>



