name: TownsAndNations
version: '${version}'
main: org.leralix.tan.TownsAndNations
api-version: "1.19"
authors: [ Leralix ]
softdepend: [Vault, PlaceholderAPI]
description: A town plugin with rp mechanics
commands:
  tan:
    description: base command of Towns and Nations
    permission: townandnation.base
    usage: /<command>
  tanadmin:
    description: admin command of Towns and Nations
    permission: townandnation.admin
    usage: /<command>
  tandebug:
    description: debug command of Towns and Nations
    permission: townandnation.admin
    usage: /<command>
  tanserver:
    description: server side command of Towns and Nations.
    permission: townandnation.server
    usage: /<command>



