package org.tan.TownsAndNations.enums;

public enum ChatCategory {

    CREATE_CITY,
    RANK_CREATION,
    RANK_RENAME,
    TOWN_DONATION,
    REGION_DONATION,
    CHANGE_TOWN_NAME,
    CHANGE_CHUNK_COLOR,
    CHANGE_TOWN_DESCRIPTION,
    CHANGE_REGION_DESCRIPTION,
    CHANGE_REGION_NAME,
    CHANGE_PROPERTY_NAME,
    CHANGE_PROPERTY_DESCRIPTION,
    CREATE_REGION
}
