package org.tan.TownsAndNations.enums;

public enum TownChunkPermissionType {
    CHEST, DOOR, BREAK, PLACE, ATTACK_PASSIVE_MOB, USE_BUTTONS, USE_REDSTONE, USE_FURNACE, INTERACT_ITEM_FRAME, INTERACT_ARMOR_STAND, DECORATIVE_BLOCK, MUSIC_BLOCK, LEAD, SHEARS
}
