package org.tan.TownsAndNations.enums;

public enum TownRolePermission {

    MANAGE_TAXES,
    PROMOTE_RANK_PLAYER,
    DERANK_RANK_PLAYER,
    CLAIM_CHUNK,
    UNCLAIM_CHUNK,
    UPGRADE_TOWN,
    INVITE_PLAYER,
    KICK_PLAYER,
    CREATE_RANK,
    DELETE_RANK,
    MANAGE_RANKS,
    MANAGE_CLAIM_SETTINGS,
    MANAGE_TOWN_RELATION,
    MANAGE_MOB_SPAWN


}