package org.leralix.tan.enums.permissions;

import org.bukkit.inventory.ItemStack;
import org.leralix.tan.dataclass.territory.permission.RelationPermission;
import org.leralix.tan.gui.cosmetic.IconKey;
import org.leralix.tan.lang.Lang;
import org.leralix.tan.lang.LangType;
import org.leralix.tan.utils.HeadUtils;

public enum ChunkPermissionType {
    INTERACT_CHEST(IconKey.GUI_MANAGE_CHEST_ACCESS_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_CHEST),
    INTERACT_DOOR(IconKey.GUI_INTERACT_DOORS_ACCESS_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_DOOR),
    BREAK_BLOCK(IconKey.GUI_BREAK_BLOCK_PERMISSION_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_BREAK),
    PLACE_BLOCK(IconKey.GUI_BUILD_BLOCK_PERMISSION_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_BUILD),
    ATTACK_PASSIVE_MOB(IconKey.GUI_ATTACK_PASSIVE_MOBS_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_ATTACK_PASSIVE_MOBS),
    INTERACT_BUTTON(IconKey.GUI_PRESS_BUTTON_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_BUTTON),
    INTERACT_REDSTONE(IconKey.GUI_USE_REDSTONE_COMPONENT, Lang.GUI_TOWN_CLAIM_SETTINGS_REDSTONE),
    INTERACT_FURNACE(IconKey.GUI_OPEN_FURNANCE_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_FURNACE),
    INTERACT_ITEM_FRAME(IconKey.GUI_INTERACT_ITEM_FRAME_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_INTERACT_ITEM_FRAME),
    INTERACT_ARMOR_STAND(IconKey.GUI_INTERACT_ARMOR_STAND_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_INTERACT_ARMOR_STAND),
    INTERACT_DECORATIVE_BLOCK(IconKey.GUI_INTERACT_CAULDRON_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_DECORATIVE_BLOCK),
    INTERACT_MUSIC_BLOCK(IconKey.GUI_INTERACT_MUSIC_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_MUSIC_BLOCK),
    USE_LEAD(IconKey.GUI_INTERACT_LEAD_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_LEAD),
    USE_SHEARS(IconKey.GUI_INTERACT_SHEARS_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_SHEARS),
    INTERACT_BOAT(IconKey.GUI_INTERACT_BOATS_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_PLACE_BOAT),
    INTERACT_MINECART(IconKey.GUI_INTERACT_MINECART_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_PLACE_VEHICLE),
    USE_BONE_MEAL(IconKey.GUI_INTERACT_BONE_MEAL_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_USE_BONE_MEAL),
    INTERACT_BERRIES(IconKey.GUI_INTERACT_GATHER_BERRIES_ICON, Lang.GUI_TOWN_CLAIM_SETTINGS_GATHER_BERRIES);

    private final IconKey iconKey;
    private final Lang label;

    ChunkPermissionType(IconKey iconKey, Lang label) {
        this.iconKey = iconKey;
        this.label = label;
    }

    public String getLabel(LangType langType) {
        return label.get(langType);
    }

    public IconKey getIconKey() {
        return iconKey;
    }

    public Lang getName(){
        return label;
    }
}
